# Generated by Django 5.0.7 on 2025-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('image', models.URLField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
