# Generated by Django 5.0.7 on 2025-03-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
