# Generated by Django 5.0.7 on 2025-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Completed', max_length=50),
        ),
    ]
