# Generated by Django 5.0.7 on 2025-03-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
