# Generated by Django 5.0.7 on 2024-12-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='img_url',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='medicine/'),
        ),
    ]
