# Generated by Django 5.0.7 on 2025-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_transaction_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.FileField(null=True, upload_to='prescriptions/'),
        ),
    ]
