# Generated by Django 5.0.7 on 2025-03-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_is_doctor_doctor_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
