# Generated by Django 5.0.7 on 2025-03-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_prescription_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.FileField(null=True, upload_to='prescriptions/'),
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
