# Generated by Django 5.0.7 on 2025-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_prescription_delete_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prescription',
            field=models.ImageField(default=1, upload_to='prescriptions/'),
            preserve_default=False,
        ),
    ]
