# Generated by Django 5.0.7 on 2025-03-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
