# Generated by Django 5.0.7 on 2025-03-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_medicine_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='Category',
        ),
    ]
