# Generated by Django 5.0.7 on 2025-03-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
