# Generated by Django 5.0.7 on 2025-03-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_medicine_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category_name',
        ),
    ]
