# Generated by Django 5.0.7 on 2025-04-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
