# Generated by Django 5.0.7 on 2025-04-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_doctor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='image',
        ),
    ]
