# Generated by Django 5.0.7 on 2025-04-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_appointment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Weeks',
            new_name='weeks',
        ),
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
