# Generated by Django 5.0.7 on 2025-04-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
