# Generated by Django 5.0.7 on 2025-03-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_userprofile_dob_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
