# Generated by Django 5.0.7 on 2025-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='degree_certificate',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='medical_license',
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
